Repository UMC-TravelStar/FE, pull requests merged in 2025-02, with the labels that each got.

#92 👽 feat: 아이디, 비밀번호 찾기 페이지 통신 구현 완료
  src/components/auth/login/loginForm.jsx
  src/components/auth/search/searchId/completedIdForm.jsx
Labels: ✨ Feature

#95 ✨ feat: 일지 작성/수정 페이지 구독 모달 추가
  src/assets/images/posts/write/delete2.png
  src/components/posts/edit/editForm.jsx
  src/components/posts/write/input/writeInput.jsx
  src/components/posts/write/modal/modal.jsx
  src/components/posts/write/writeForm.jsx
  src/styles/posts/write/write.js
  src/utils/posts/edit/toggleData.js
Labels: ✨ Feature

#98 ♻️ refactor: 캘린더 우측 컴포넌트 UI 수정
  src/assets/images/calender/add.png
  src/assets/images/calender/toggle.png
  src/assets/images/calender/trash.png
  src/components/calender/calenderLeft/calenderLeft.jsx
  src/components/calender/calenderRight/addModal.jsx
  src/components/calender/calenderRight/calenderRight.jsx
  src/components/calender/calenderRight/editModal.jsx
  src/components/calender/calenderRight/item-calender.jsx
  src/components/calender/calenderRight/list-calender.jsx
  src/components/calender/calenderRight/modalTime.jsx
  src/components/calender/calenderRight/placeModal.jsx
  src/pages/calender/calender.jsx
  src/styles/calender/calender.js
  src/styles/common/colors.js
Labels: ✨ Feature

#101 🐛 fix: 랭킹 좌측 UI 렌더링 오류 수정
  src/components/ranking/rankingLeft/bottom/list-bottomRanking.jsx
  src/components/ranking/rankingLeft/rankingLeft.jsx
  src/components/ranking/rankingLeft/top/list-topRanking.jsx
  src/styles/ranking/ranking.js
Labels: 🐞 Bug

#103 👽 feature: sideBar, 일지 작성, 랭킹 조회 1차 통신 완료
  src/components/auth/login/loginForm.jsx
  src/components/posts/write/writeForm.jsx
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/rankingLeft.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/components/ranking/rankingLeft/top/list-topRanking.jsx
  src/components/sideBar/profile.jsx
  src/hooks/useFetch.js
  src/pages/ranking/ranking.jsx
Labels: ✨ Feature

#106 Feature/woojo230 planet#105
  src/pages/auth/setting/setting.jsx
  src/pages/planet/planet.jsx
Labels: ✨ Feature

#109 👽 feat: 캘린더 API 연결 중
  src/components/calender/calenderLeft/calenderLeft.jsx
  src/components/calender/calenderRight/addModal.jsx
  src/components/calender/calenderRight/calenderRight.jsx
  src/components/calender/calenderRight/item-calender.jsx
  src/components/calender/calenderRight/list-calender.jsx
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/bottom/list-bottomRanking.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/components/ranking/rankingLeft/top/list-topRanking.jsx
  src/components/ranking/rankingRight/rankingRight.jsx
  src/pages/calender/calender.jsx
  src/pages/ranking/ranking.jsx
  src/styles/calender/calender.js
Labels: ✨ Feature

#114 🐛 fix: 로그인 경로 수정
  src/components/auth/login/loginForm.jsx
  src/hooks/useFetch.js
Labels: 🐞 Bug

#120 ✨ feat: 다른 사람 행성 보기 통신 연결
  src/pages/planet/othersPlanet.jsx
  src/pages/planet/planet.jsx
Labels: ✨ Feature

#122 ✨ feat: 행성 설정 페이지 경로 수정
  src/pages/auth/setting/setting.jsx
  src/pages/planet/planet.jsx
  src/utils/planet/getRandom.js
Labels: ✨ Feature

#123 ⏪ revert: 캘린더페이지 코드 롤백
  src/components/calender/calenderLeft/calenderLeft.jsx
  src/components/calender/calenderRight/addModal.jsx
  src/components/calender/calenderRight/calenderRight.jsx
  src/components/calender/calenderRight/editModal.jsx
  src/components/calender/calenderRight/item-calender.jsx
  src/components/calender/calenderRight/list-calender.jsx
  src/components/calender/calenderRight/modalTime.jsx
  src/pages/calender/calender.jsx
Labels: help wanted

#124 👽 feat: 랭킹 투표 통신 완료
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/bottom/list-bottomRanking.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/components/ranking/rankingLeft/top/list-topRanking.jsx
  src/components/ranking/rankingRight/rankingRight.jsx
  src/styles/ranking/ranking.js
Labels: ✨ Feature

#128 👽 feat: 일지작성 페이지 s3 통신 완료
  src/components/posts/write/writeForm.jsx
Labels: ✨ Feature

#132 ✨ feat: 별자리 통신 연결 & 로직 수정
  src/components/planet/ConstellationViewer.jsx
  src/pages/planet/planet.jsx
Labels: ✨ Feature

#135 🐞 bug: 별자리 생성 및 행성 보기 페이지 api 연결 수정
  src/components/planet/ConstellationViewer.jsx
  src/hooks/useProcessRegionData.js
  src/pages/planet/planet.jsx
  src/utils/constellationviwer/adjustPointPositions.js
  src/utils/constellationviwer/canvasRenderer.js
  src/utils/constellationviwer/mstUtils.js
Labels: 🐞 Bug

#136 ✨ feat: 캘린더 api 연결
  src/apis/planet/planetService.js
  src/components/calender/calenderRight/addModal.jsx
  src/components/calender/calenderRight/calenderRight.jsx
  src/components/calender/calenderRight/editModal.jsx
  src/components/calender/calenderRight/item-calender.jsx
  src/components/calender/calenderRight/list-calender.jsx
Labels: ✨ Feature

#137 👽 feat: 일지작성 페이지 통신 완료
  src/components/posts/write/modal/feelingModal.jsx
  src/components/posts/write/textarea/writeTextarea.jsx
  src/components/posts/write/writeForm.jsx
  src/utils/posts/write/feelingData.js
Labels: ✨ Feature

#142 👽 feat: 일지작성 페이지 feeling 필드 전송 추가
  src/components/posts/write/writeForm.jsx
Labels: ✨ Feature

#147 👽 feat: 행성 이름 확인 API 수정
  src/components/auth/login/loginForm.jsx
  src/components/sideBar/profile.jsx
Labels: 🐞 Bug

#149 👽 feat: 랭킹페이지 확인 API 연결 완료
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/components/ranking/rankingRight/rankingRight.jsx
Labels: ✨ Feature

#156 ✨ feat: 행성 보기 페이지 일지 상세 페이지 연결
  src/pages/planet/othersPlanet.jsx
  src/pages/planet/planet.jsx
Labels: ✨ Feature

#159 🗃️ Comment: 구독 모달 주석처리
  src/apis/posts/spotifyService.js
  src/components/posts/edit/editForm.jsx
  src/components/posts/write/writeForm.jsx
  src/hooks/useMusic.js
Labels: ✨ Feature

#162 ♻️ refactor: 마이페이지 코드 리팩토링
  src/assets/images/sideBar/profile.png
  src/components/sideBar/profile.jsx
  src/pages/auth/mypage/mypage.jsx
  src/styles/common/sidebar/sidebar.js
Labels: ✨ Feature

#166 👽 feat: 캘린더 오류 해결
  src/components/calender/calenderRight/editModal.jsx
  src/components/calender/calenderRight/list-calender.jsx
  src/styles/calender/calender.js
Labels: 🐞 Bug

#176 👽 feat: 랭킹 state 값 전달 및 캘린더 css 수정
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/styles/calender/calender.js
Labels: ✨ Feature

#184 🐛 fix: 랭킹페이지 오류 수정
  src/components/ranking/rankingLeft/bottom/item-bottomRanking.jsx
  src/components/ranking/rankingLeft/top/item-topRanking.jsx
  src/components/ranking/rankingRight/rankingRight.jsx
  src/styles/ranking/ranking.js
Labels: 🐞 Bug

#185 ✨ feat: 다른 사람 행성 보기 다른 사람 일지 보기 연결
  src/pages/planet/othersPlanet.jsx
Labels: ✨ Feature

#194 🎨 Design: sideBar css 수정
  src/styles/common/sidebar/sidebar.js
Labels: 🐞 Bug

#195 ✨ feat: 비밀번호 수정 로직 추가
  src/components/auth/search/searchPassword/searchPasswordForm.jsx
Labels: ✨ Feature

#197 🎨 Design: 캘린더페이지 css 수정
  src/components/calender/calenderLeft/calenderLeft.jsx
  src/styles/calender/calender.js
Labels: 🐞 Bug

#199 🎨 Design: planet 페이지 반응형으로 수정 중
  src/pages/planet/planet.jsx
Labels: 🐞 Bug

#202 🐛 fix: 모바일 기기 이미지 업로드 문제 해결 중
  src/components/posts/write/writeForm.jsx
Labels: 🐞 Bug

#203 🐛 fix: 일지수정 업로드 오류 수정
  src/components/posts/edit/editForm.jsx
  src/components/posts/posts/Tabs/friend-card.jsx
  src/pages/auth/mypage/friends.jsx
  src/pages/auth/mypage/posts.jsx
Labels: 🐞 Bug
